### ISSUE TITLE
WinrtServer winrt C++ projections are not available in client projects

### ISSUE THREAD

**Issue by forderud** [jogerh/com_samples#28]
The TutorialsAndTests project only seem to access WinrtServer through the low-level `ABI` interface, instead of the "modern" `winrt` C++ projection that automatically converts HRESULTs to exceptions and output arguments to return-values. This makes the client code more complex than neccesary.

Root-cause seem to be the `winmdidl` call in CreateCppInterop.bat. I think replacing it with a `cppwinrt.exe` call (found in Microsoft.Windows.CppWinRT NuGet) would make the generated headers include `winrt` C++ projections. Alternatively, just copy the already generated headers from the `WinrtServer\Generated Files\winrt` folder.

**Comment by forderud** [comment]
@jogerh Any thoughts on this?

**Comment by jogerh** [comment]
Yup. This is absolutely a better approach. I'll give it a shot.

**Comment by forderud** [comment]
A recursive `xcopy` command would probably be simplest here. This will unfortunately also copy over a lot of generated Windows headers that should probably not have been generated in the first place. I unfortunately don't know how to fix that annoyance, but guess it can be tackled later.

**Comment by jogerh** [comment]
Thanks for inputs @forderud. This was exactly what I needed to understand how to get something working in PR #30
